### ISSUE TITLE
Mondido.JS library doesn't work with new versions of jQuery

### ISSUE THREAD

**Issue by 1151k** [Mondido/mondido-js#2]
In 5 different places there's the use of `.size()` in the JS library, breaking the script if one uses newer versions of jQuery. I'd recommend changing those pieces of code with `.length > 0` or something similar.

**Comment by mondido-slava** [comment]
Thank's for reporting.
How can I replicate the error? @DanielLisik

**Comment by mondido-slava** [comment]
fix deployed.
